import type { DailyPathConfig } from "@/types/dailyPath";

export const ENERGY_CONGRUENCE_DEEP_RO: DailyPathConfig = {
  id: "energy_congruence_deep_ro",
  cluster: "focus_energy_cluster",
  mode: "deep",
  lang: "ro",
  version: 1,
  moduleKey: "energy_congruence",
  skillLabel: "Energie: alegeri congruente",
  autonomyNodeId: "energy_congruence_autonomy",
  nodes: [
    {
      id: "energy_congruence_intro",
      kind: "INTRO",
      shape: "circle",
      title: "Energie prin congruență",
      description:
        "Astăzi lucrăm cu un tip invizibil de pierdere de energie.\nNu din lipsă de somn sau pauze, ci din conflict interior — când faci lucruri care nu sunt în acord cu tine.\nVei învăța să recunoști această scurgere și să o oprești printr-o alegere conștientă.\nAzi nu e despre pauze sau respirație, ci despre energia pe care o pierzi din conflict interior.",
      xp: 0,
      ctaLabel: "Începe antrenamentul",
    },
    {
      id: "energy_congruence_learn1",
      kind: "LEARN",
      shape: "circle",
      title: "Ce înseamnă congruența",
      description:
        "Congruența înseamnă să existe acord între ce simți, ce gândești și ce faci.\nNu înseamnă că totul e confortabil sau ușor.\nÎnseamnă că nu te mai tragi singur în direcții opuse.",
      xp: 5,
    },
    {
      id: "energy_congruence_example",
      kind: "LEARN",
      shape: "circle",
      title: "O zi care te obosește invizibil",
      description:
        "Ana spune „da” la lucruri pe care nu le vrea cu adevărat.\nZâmbește, se conformează, încearcă să nu dezamăgească.\nSeara e epuizată și simte tensiune în umeri, deși ziua n-a fost extremă ca volum.\nOboseala vine din conflictul interior, nu din efort.",
      xp: 5,
    },
    {
      id: "energy_congruence_quiz1",
      kind: "QUIZ_SINGLE",
      shape: "circle",
      title: "Recunoaște scurgerea",
      description: "Care situație consumă cel mai mult energie?",
      quizOptions: [
        { id: "A", label: "O oră de muncă concentrată la ceva ales de tine." },
        { id: "B", label: "Să faci ceva doar ca să fii acceptat, deși nu vrei." },
        { id: "C", label: "O plimbare liniștită fără telefon." },
      ],
      correctOptionIds: ["B"],
      quizFeedback: {
        correct: "Exact. Conflictul interior consumă energie constant. Probabil ai simțit asta deja, chiar dacă nu ai numit-o așa.",
        incorrect: "Nu chiar. Efortul nu te epuizează cel mai tare — ci lupta cu tine.",
      },
      xp: 10,
    },
    {
      id: "energy_congruence_learn2",
      kind: "LEARN",
      shape: "circle",
      title: "De ce apare conflictul",
      description:
        "Conflictul apare când:\n– trăiești pentru a fi plăcut,\n– te compari constant,\n– încerci să controlezi ce nu ține de tine.\nCongruența nu înseamnă să faci doar ce îți place, ci să știi când alegi și când te sacrifici conștient.\nToate creează fricțiune și scurg energie.",
      xp: 5,
    },
    {
      id: "energy_congruence_quiz2",
      kind: "QUIZ_SINGLE",
      shape: "circle",
      title: "Aplică regula",
      description: "Care formulare indică mai multă congruență?",
      quizOptions: [
        { id: "A", label: "„Trebuie să fac asta, chiar dacă nu vreau.”" },
        { id: "B", label: "„Aleg să fac asta, chiar dacă nu e ușor.”" },
        { id: "C", label: "„Fac asta ca să nu supăr pe nimeni.”" },
      ],
      correctOptionIds: ["B"],
      quizFeedback: {
        correct: "Da. Alegerea conștientă reduce conflictul interior. Probabil ai simțit asta deja, chiar dacă nu ai numit-o așa.",
        incorrect: "Aproape. Congruența începe când recunoști că alegi.",
      },
      xp: 10,
    },
    {
      id: "energy_congruence_sim1",
      kind: "SIMULATOR",
      shape: "circle",
      badge: "simulator",
      title: "Simulator: unde te tragi pe tine înapoi",
      description:
        "În timp ce cercul se mișcă, observă o situație recentă:\n– unde ai spus „da”, dar ai simțit „nu”?\nNu schimba nimic. Doar observă senzația din corp.\nPoate apărea ca tensiune în piept, greutate în stomac, agitație — sau nimic clar (și asta e ok).",
      xp: 15,
      ctaLabel: "Exercițiul e gata",
    },
    {
      id: "energy_congruence_autonomy",
      kind: "ACTION",
      shape: "star",
      title: "Cum te simți după prima observare?",
      description: "Alege pasul următor.",
      xp: 0,
    },
    {
      id: "energy_congruence_sim2",
      kind: "SIMULATOR",
      shape: "hollow",
      badge: "simulator",
      softPathOnly: true,
      title: "Extra training: o micro-alegere",
      description:
        "Alege o situație mică din ziua de azi.\nFormulează mental: „Aleg să fac / să nu fac asta pentru că…”\nObservă dacă tensiunea scade.",
      xp: 5,
      ctaLabel: "Exercițiul e gata",
    },
    {
      id: "energy_congruence_learn3",
      kind: "LEARN",
      shape: "circle",
      title: "Semne că ești aliniat",
      description:
        "Alinierea nu se simte ca entuziasm.\nSe simte ca:\n– mai puțină tensiune,\n– mai puține justificări,\n– mai puțină amânare.",
      xp: 5,
    },
    {
      id: "energy_congruence_real",
      kind: "REAL_WORLD",
      shape: "star",
      badge: "viata_reala",
      title: "Provocarea reală de azi",
      description: "Scrie situația și alegerea congruentă. Alege ceva mic și realist, care se poate întâmpla azi.",
      fields: [
        {
          id: "situation",
          label: "Azi, într-o situație ca aceasta:",
          placeholder: "ex: când cineva îmi cere mai mult decât pot oferi",
        },
        {
          id: "decision",
          label: "Alegerea mea congruentă va fi:",
          placeholder: "ex: Aleg să spun nu ferm, chiar dacă dezamăgesc.",
        },
      ],
      xp: 25,
      ctaLabel: "Mă angajez",
    },
    {
      id: "energy_congruence_summary",
      kind: "SUMMARY",
      shape: "circle",
      title: "Felicitări, ai terminat antrenamentul de azi.",
      description: "",
      bullets: [
        "Energia se pierde în conflict interior, nu doar în efort.",
        "Congruența reduce fricțiunea internă.",
        "O micro-alegere aliniată conservă energie.",
        "Nu trebuie să rezolvi tot. E suficient să nu te mai lupți cu tine.",
      ],
      anchorDescription: "Aleg din viața mea, nu pentru exterior.",
      xp: 0,
      ctaLabel: "Vezi progresul",
    },
    {
      id: "energy_congruence_anchor",
      kind: "ANCHOR",
      shape: "circle",
      title: "Motto zilnic",
      description: "Aleg din viața mea, nu pentru exterior.",
      xp: 0,
      ctaLabel: "Gata pe azi",
    },
  ],
};
