import type { DailyPathConfig } from "@/types/dailyPath";

export const ENERGY_CONGRUENCE_DEEP_EN: DailyPathConfig = {
  id: "energy_congruence_deep_en",
  cluster: "focus_energy_cluster",
  mode: "deep",
  lang: "en",
  version: 1,
  moduleKey: "energy_congruence",
  skillLabel: "Energy: congruent choices",
  autonomyNodeId: "energy_congruence_autonomy",
  nodes: [
    {
      id: "energy_congruence_intro",
      kind: "INTRO",
      shape: "circle",
      title: "Energy through congruence",
      description:
        "Today we work with a mostly invisible energy leak.\nNot caused by lack of sleep or breaks, but by inner conflict — doing things that are not aligned with you.\nYou’ll learn to notice this leak and stop it through one conscious choice.\nToday isn’t about breaks or breathing — it’s about energy you lose through inner conflict.",
      xp: 0,
      ctaLabel: "Start training",
    },
    {
      id: "energy_congruence_learn1",
      kind: "LEARN",
      shape: "circle",
      title: "What it means to be congruent",
      description:
        "Congruence means alignment between what you feel, think, and do.\nIt doesn’t mean things are comfortable or easy.\nIt means you’re no longer pulling yourself in opposite directions.",
      xp: 5,
    },
    {
      id: "energy_congruence_example",
      kind: "LEARN",
      shape: "circle",
      title: "A day drained from the inside",
      description:
        "Ana says “yes” to things she doesn’t really want.\nShe smiles, adapts, avoids disappointing anyone.\nAt the end of the day she’s exhausted and feels tension in her shoulders, even though workload was moderate.\nThe fatigue comes from inner conflict, not effort.",
      xp: 5,
    },
    {
      id: "energy_congruence_quiz1",
      kind: "QUIZ_SINGLE",
      shape: "circle",
      title: "Spot the energy leak",
      description: "Which situation drains the most energy?",
      quizOptions: [
        { id: "A", label: "One hour of focused work on something you chose." },
        { id: "B", label: "Doing something just to be accepted, even though you don’t want to." },
        { id: "C", label: "A calm walk without your phone." },
      ],
      correctOptionIds: ["B"],
      quizFeedback: {
        correct: "Exactly. Inner conflict is a constant drain. You’ve probably felt this before, even if you never named it.",
        incorrect: "Not quite. Effort is not the main drain — fighting yourself is.",
      },
      xp: 10,
    },
    {
      id: "energy_congruence_learn2",
      kind: "LEARN",
      shape: "circle",
      title: "Where conflict comes from",
      description:
        "Conflict appears when you:\n– live to please others,\n– compare yourself constantly,\n– try to control what isn’t yours to control.\nCongruence doesn’t mean doing only what you like — it means knowing when you’re choosing and when you’re consciously sacrificing.\nEach creates friction and leaks energy.",
      xp: 5,
    },
    {
      id: "energy_congruence_quiz2",
      kind: "QUIZ_SINGLE",
      shape: "circle",
      title: "Apply congruence",
      description: "Which sentence shows more congruence?",
      quizOptions: [
        { id: "A", label: "“I have to do this, even though I don’t want to.”" },
        { id: "B", label: "“I choose to do this, even if it’s not easy.”" },
        { id: "C", label: "“I do this so no one gets upset.”" },
      ],
      correctOptionIds: ["B"],
      quizFeedback: {
        correct: "Yes. Conscious choice reduces inner conflict. You’ve probably felt this before, even if you never named it.",
        incorrect: "Almost. Congruence starts when you recognize choice.",
      },
      xp: 10,
    },
    {
      id: "energy_congruence_sim1",
      kind: "SIMULATOR",
      shape: "circle",
      badge: "simulator",
      title: "Simulator: where you hold yourself back",
      description:
        "While the circle moves, recall a recent situation:\n– where did you say “yes” while feeling “no”?\nDon’t change anything. Just notice the sensation in your body.\nYou might notice chest tension, a heavy stomach, restlessness — or nothing clear (that’s okay).",
      xp: 15,
      ctaLabel: "Exercise done",
    },
    {
      id: "energy_congruence_autonomy",
      kind: "ACTION",
      shape: "star",
      title: "How do you feel after observing?",
      description: "Choose your next step.",
      xp: 0,
    },
    {
      id: "energy_congruence_sim2",
      kind: "SIMULATOR",
      shape: "hollow",
      badge: "simulator",
      softPathOnly: true,
      title: "Extra training: a micro-choice",
      description:
        "Pick a small situation from today.\nMentally state: “I choose to do / not do this because…”\nNotice whether the tension decreases.",
      xp: 5,
      ctaLabel: "Exercise done",
    },
    {
      id: "energy_congruence_learn3",
      kind: "LEARN",
      shape: "circle",
      title: "Signs of alignment",
      description:
        "Alignment doesn’t feel like fireworks.\nIt feels like:\n– less tension,\n– fewer justifications,\n– less procrastination.",
      xp: 5,
    },
    {
      id: "energy_congruence_real",
      kind: "REAL_WORLD",
      shape: "star",
      badge: "viata_reala",
      title: "Your real-life challenge today",
      description: "Write the situation and your congruent choice. Choose something small and realistic that can happen today.",
      fields: [
        {
          id: "situation",
          label: "Today, in a situation like:",
          placeholder: "e.g., when someone asks for more than I can give",
        },
        {
          id: "decision",
          label: "My congruent choice will be:",
          placeholder: "e.g., I choose to say no calmly, even if someone is disappointed",
        },
      ],
      xp: 25,
      ctaLabel: "I commit",
    },
    {
      id: "energy_congruence_summary",
      kind: "SUMMARY",
      shape: "circle",
      title: "Great job — today’s training is complete.",
      description: "",
      bullets: [
        "Energy is drained by inner conflict, not just effort.",
        "Congruence reduces internal friction.",
        "One aligned micro-choice preserves energy.",
        "You don’t have to fix everything. It’s enough to stop fighting yourself.",
      ],
      anchorDescription: "I choose from my life, not for the outside.",
      xp: 0,
      ctaLabel: "See your progress",
    },
    {
      id: "energy_congruence_anchor",
      kind: "ANCHOR",
      shape: "circle",
      title: "Daily motto",
      description: "I choose from my life, not for the outside.",
      xp: 0,
      ctaLabel: "Done for today",
    },
  ],
};
