import type { DailyPathConfig } from "@/types/dailyPath";

export const EMO_FLEX_NAMING_DEEP_EN: DailyPathConfig = {
  id: "flexibility_naming_emotion_deep_en",
  cluster: "emotional_flex_cluster",
  mode: "deep",
  lang: "en",
  version: 1,
  moduleKey: "emotional_flex_naming",
  skillLabel: "Emotional Flex: name the emotion",
  autonomyNodeId: "emo_flex_naming_autonomy_en",
  nodes: [
    {
      id: "emo_flex_naming_intro_en",
      kind: "INTRO",
      shape: "circle",
      title: "Naming the emotion",
      description:
        "Today you’ll train the first step of emotional flexibility: naming what you feel.\nNot to analyze the emotion, but to create space between feeling and reaction.",
      xp: 0,
      ctaLabel: "Start training",
    },
    {
      id: "emo_flex_naming_learn1_en",
      kind: "LEARN",
      shape: "circle",
      title: "The unnoticed emotion",
      description:
        "When an emotion isn’t recognized, it automatically drives behavior.\nYou don’t choose — you react.\nFlexibility begins when you name what you feel.",
      xp: 5,
    },
    {
      id: "emo_flex_naming_example_en",
      kind: "LEARN",
      shape: "circle",
      title: "Automatic reaction",
      description:
        "Mihai receives a short, cold message.\nHe feels something but doesn’t name it, and responds defensively.\nLater he says: “I don’t know why I reacted like that.”\nHe reacted from an unnamed emotion.",
      xp: 5,
    },
    {
      id: "emo_flex_naming_quiz1_en",
      kind: "QUIZ_SINGLE",
      shape: "circle",
      title: "Recognize it",
      description: "What usually happens when you don’t recognize an emotion?",
      quizOptions: [
        { id: "A", label: "The emotion disappears." },
        { id: "B", label: "The emotion drives the reaction." },
        { id: "C", label: "You become more rational." },
      ],
      correctOptionIds: ["B"],
      quizFeedback: {
        correct: "Exactly. Unnamed emotions take control.",
        incorrect: "Not quite. Ignored emotions tend to drive reactions.",
      },
      xp: 10,
    },
    {
      id: "emo_flex_naming_learn2_en",
      kind: "LEARN",
      shape: "circle",
      title: "Why naming works",
      description:
        "Naming an emotion doesn’t amplify it.\nIt makes it visible.\nWhen you say “I feel frustration” or “I feel anxiety,” you create distance between emotion and action.",
      xp: 5,
    },
    {
      id: "emo_flex_naming_quiz2_en",
      kind: "QUIZ_SINGLE",
      shape: "circle",
      title: "Create space",
      description: "Which sentence creates more space?",
      quizOptions: [
        { id: "A", label: "“I’m angry, so I react.”" },
        { id: "B", label: "“I notice anger right now.”" },
        { id: "C", label: "“This shouldn’t affect me.”" },
      ],
      correctOptionIds: ["B"],
      quizFeedback: {
        correct: "Yes. Observation creates space for choice.",
        incorrect: "Almost. Flexibility starts with observation, not judgment.",
      },
      xp: 10,
    },
    {
      id: "emo_flex_naming_sim1_en",
      kind: "SIMULATOR",
      shape: "circle",
      badge: "simulator",
      title: "Simulator: name the emotion",
      description:
        "While the circle moves, bring to mind a recent situation.\nAsk simply: “What emotion do I feel right now?”\nIt can be basic: anger, fear, sadness, shame, frustration — or “I don’t know.”",
      xp: 15,
      ctaLabel: "Exercise done",
    },
    {
      id: "emo_flex_naming_autonomy_en",
      kind: "ACTION",
      shape: "star",
      title: "How do you want to continue?",
      description: "Choose your next step.",
      xp: 0,
    },
    {
      id: "emo_flex_naming_sim2_en",
      kind: "SIMULATOR",
      shape: "hollow",
      badge: "simulator",
      softPathOnly: true,
      title: "Extra training: the emotion sentence",
      description:
        "Form a short sentence in your mind: “I notice that I feel ___.”\nDon’t change anything. Just observe the effect.",
      xp: 5,
      ctaLabel: "Exercise done",
    },
    {
      id: "emo_flex_naming_learn3_en",
      kind: "LEARN",
      shape: "circle",
      title: "Signs of flexibility",
      description:
        "Emotional flexibility doesn’t mean instant calm.\nIt means less impulsivity, a brief pause, and more choice.",
      xp: 5,
    },
    {
      id: "emo_flex_naming_real_en",
      kind: "REAL_WORLD",
      shape: "star",
      badge: "viata_reala",
      title: "Your real-life challenge",
      description: "Describe the situation and your sentence.",
      fields: [
        {
          id: "context",
          label: "Situation where I’ll name the emotion:",
          placeholder: "e.g., when I receive a difficult message",
        },
        {
          id: "sentence",
          label: "My sentence will be:",
          prefix: "I notice that I feel ",
          suffix: ".",
          placeholder: "describe the emotion",
        },
      ],
      xp: 25,
      ctaLabel: "I commit",
    },
    {
      id: "emo_flex_naming_summary_en",
      kind: "SUMMARY",
      shape: "circle",
      title: "Great job — today’s training is complete.",
      description: "",
      bullets: [
        "Unnamed emotions drive reactions.",
        "Naming creates space for choice.",
        "One word can change the response.",
      ],
      anchorDescription: "Notice. Name. Choose.",
      xp: 0,
      ctaLabel: "See your progress",
    },
    {
      id: "emo_flex_naming_anchor_en",
      kind: "ANCHOR",
      shape: "circle",
      title: "Daily motto",
      description: "Notice. Name. Choose.",
      xp: 0,
      ctaLabel: "Done for today",
    },
  ],
};
