import type { DailyPathConfig } from "@/types/dailyPath";

export const EMO_FLEX_NAMING_DEEP_RO: DailyPathConfig = {
  id: "flexibility_naming_emotion_deep_ro",
  cluster: "emotional_flex_cluster",
  mode: "deep",
  lang: "ro",
  version: 1,
  moduleKey: "emotional_flex_naming",
  skillLabel: "Flexibilitate: numește emoția",
  autonomyNodeId: "emo_flex_naming_autonomy_ro",
  nodes: [
    {
      id: "emo_flex_naming_intro_ro",
      kind: "INTRO",
      shape: "circle",
      title: "Naming the emotion",
      description:
        "Astăzi lucrăm cu primul pas al flexibilității emoționale: să numești ce simți.\nNu pentru a analiza emoția, ci pentru a crea spațiu între tine și reacție.",
      xp: 0,
      ctaLabel: "Încep",
    },
    {
      id: "emo_flex_naming_learn1_ro",
      kind: "LEARN",
      shape: "circle",
      title: "Emoția neobservată",
      description:
        "Când o emoție nu este recunoscută, ea conduce automat comportamentul.\nNu alegi ce faci — reacționezi.\nPrimul pas spre flexibilitate este să pui un nume simplu pe ce simți.",
      xp: 5,
    },
    {
      id: "emo_flex_naming_example_ro",
      kind: "LEARN",
      shape: "circle",
      title: "Când emoția conduce",
      description:
        "Mihai primește un mesaj scurt și rece.\nSimte ceva, dar nu își dă seama ce. Răspunde defensiv.\nMai târziu își spune: „Nu știu de ce am reacționat așa.”\nA reacționat dintr-o emoție nenumită.",
      xp: 5,
    },
    {
      id: "emo_flex_naming_quiz1_ro",
      kind: "QUIZ_SINGLE",
      shape: "circle",
      title: "Recunoaște emoția",
      description: "Ce se întâmplă cel mai des când nu recunoști emoția?",
      quizOptions: [
        { id: "A", label: "Emoția dispare de la sine." },
        { id: "B", label: "Emoția conduce reacția." },
        { id: "C", label: "Devii mai rațional." },
      ],
      correctOptionIds: ["B"],
      quizFeedback: {
        correct: "Exact. Emoția nenumită preia controlul.",
        incorrect: "Nu chiar. Emoțiile ignorate tind să conducă reacțiile.",
      },
      xp: 10,
    },
    {
      id: "emo_flex_naming_learn2_ro",
      kind: "LEARN",
      shape: "circle",
      title: "Puterea denumirii",
      description:
        "A numi emoția nu o amplifică.\nO face vizibilă.\nCând spui „simt frustrare” sau „simt anxietate”, creezi o mică distanță între emoție și acțiune.",
      xp: 5,
    },
    {
      id: "emo_flex_naming_quiz2_ro",
      kind: "QUIZ_SINGLE",
      shape: "circle",
      title: "Creează spațiu",
      description: "Care formulare creează mai mult spațiu?",
      quizOptions: [
        { id: "A", label: "„Sunt nervos, deci reacționez.”" },
        { id: "B", label: "„Simt nervozitate chiar acum.”" },
        { id: "C", label: "„Asta nu ar trebui să mă afecteze.”" },
      ],
      correctOptionIds: ["B"],
      quizFeedback: {
        correct: "Da. Observarea creează spațiu pentru alegere.",
        incorrect: "Aproape. Flexibilitatea începe cu observarea, nu cu judecata.",
      },
      xp: 10,
    },
    {
      id: "emo_flex_naming_sim1_ro",
      kind: "SIMULATOR",
      shape: "circle",
      badge: "simulator",
      title: "Simulator: numește emoția",
      description:
        "În timp ce cercul se mișcă, adu în minte o situație recentă.\nÎntreabă-te simplu: „Ce emoție simt acum?”\nPoate fi una simplă: furie, frică, tristețe, rușine, frustrare — sau „nu știu”.",
      xp: 15,
      ctaLabel: "Exercițiul e gata",
    },
    {
      id: "emo_flex_naming_autonomy_ro",
      kind: "ACTION",
      shape: "star",
      title: "Cum vrei să continui?",
      description: "Alege pasul următor.",
      xp: 0,
    },
    {
      id: "emo_flex_naming_sim2_ro",
      kind: "SIMULATOR",
      shape: "hollow",
      badge: "simulator",
      softPathOnly: true,
      title: "Extra training: propoziția emoției",
      description:
        "Formulează mental o propoziție scurtă: „Observ că simt __.”\nNu schimba nimic. Doar observă efectul.",
      xp: 5,
      ctaLabel: "Exercițiul e gata",
    },
    {
      id: "emo_flex_naming_learn3_ro",
      kind: "LEARN",
      shape: "circle",
      title: "Semnul flexibilității",
      description:
        "Flexibilitatea emoțională nu înseamnă calm instant.\nÎnseamnă mai puțină impulsivitate, un mic spațiu înainte de reacție și mai multă alegere.",
      xp: 5,
    },
    {
      id: "emo_flex_naming_real_ro",
      kind: "REAL_WORLD",
      shape: "star",
      badge: "viata_reala",
      title: "Provocarea reală de azi",
      description: "Scrie situația și propoziția ta.",
      fields: [
        {
          id: "context",
          label: "Situația în care voi numi emoția:",
          placeholder: "ex: când primesc un mesaj dificil",
        },
        {
          id: "sentence",
          label: "Propoziția mea va fi:",
          prefix: "Observ că simt ",
          suffix: ".",
          placeholder: "descrie emoția",
        },
      ],
      xp: 25,
      ctaLabel: "Mă angajez",
    },
    {
      id: "emo_flex_naming_summary_ro",
      kind: "SUMMARY",
      shape: "circle",
      title: "Felicitări, ai terminat antrenamentul de azi.",
      description: "",
      bullets: [
        "Emoțiile nenumite conduc reacțiile.",
        "Denumirea creează spațiu pentru alegere.",
        "Un cuvânt poate schimba răspunsul.",
      ],
      anchorDescription: "Observ. Numez. Aleg.",
      xp: 0,
      ctaLabel: "Vezi progresul",
    },
    {
      id: "emo_flex_naming_anchor_ro",
      kind: "ANCHOR",
      shape: "circle",
      title: "Motto zilnic",
      description: "Observ. Numez. Aleg.",
      xp: 0,
      ctaLabel: "Gata pe azi",
    },
  ],
};
