import type { DailyPathConfig } from "@/types/dailyPath";

export const EMOTIONAL_FLEX_SHORT_RO: DailyPathConfig = {
  id: "emotional_flex_v1_short_ro",
  cluster: "emotional_flex_cluster",
  mode: "short",
  lang: "ro",
  version: 1,
  moduleKey: "emotional_flex_pause",
  skillLabel: "Flexibilitate: micro-pauză înainte de reacție",
  nodes: [
    {
      id: "emoflex_short_intro",
      kind: "INTRO",
      shape: "circle",
      title: "Flexibilitate emoțională — Scurt",
      description: "Un antrenament scurt și clar care te ajută să rămâi flexibil sub presiune.",
      xp: 0,
      ctaLabel: "Încep",
    },
    {
      id: "emoflex_short_learn",
      kind: "LEARN",
      shape: "circle",
      title: "Capcana tensiune → reacție",
      description: "Emoțiile îngustează atenția. Flexibilitatea o lărgește înainte de acțiune.",
      xp: 5,
    },
    {
      id: "emoflex_short_quiz",
      kind: "QUIZ_SINGLE",
      shape: "circle",
      title: "Observă momentul critic",
      description: "Ce te ajută să eviți hijack-ul emoțional?",
      quizOptions: [
        { id: "A", label: "Să aștepți să treacă emoția" },
        { id: "B", label: "Să creezi 2 secunde de spațiu" },
        { id: "C", label: "Să ignori ce simți" },
      ],
      correctOptionIds: ["B"],
      quizFeedback: {
        correct: "Exact. Spațiul de 2 secunde îți păstrează flexibilitatea.",
        incorrect: "Ignorarea emoției nu funcționează. Creează spațiu înainte să reacționezi.",
      },
      xp: 10,
    },
    {
      id: "emoflex_short_sim",
      kind: "SIMULATOR",
      shape: "circle",
      badge: "simulator",
      title: "Micro-pauză de 2 secunde",
      description: "Exersează un ciclu: Observ → Pauză → Expir lent. Acesta este comutatorul tău de flexibilitate.",
      simulatorConfig: { inhaleSeconds: 2, exhaleSeconds: 2 },
      xp: 10,
      ctaLabel: "Am făcut exercițiul",
    },
    {
      id: "emoflex_short_real",
      kind: "REAL_WORLD",
      shape: "star",
      badge: "viata_reala",
      title: "Folosește-l în viața reală",
      description:
        "Alege o situație de azi unde poate apărea tensiune și stabilește acțiunea ta de 2 secunde.",
      fields: [
        {
          id: "context",
          label: "Un moment azi în care pot simți tensiune…",
          placeholder: "ex: înainte de statusul de după-amiază",
        },
        {
          id: "rule",
          label: "Acțiunea mea:",
          prefix: "În acel moment → Pauzez 2 secunde și",
          placeholder: "ex: inspir, numesc emoția și formulez răspunsul.",
        },
      ],
      xp: 20,
      ctaLabel: "Îmi iau angajamentul",
    },
    {
      id: "emoflex_short_summary",
      kind: "SUMMARY",
      shape: "circle",
      title: "Azi ai antrenat flexibilitatea",
      description: "",
      bullets: [
        "Ai identificat tensiunea emoțională devreme.",
        "Ai exersat micro-pauza.",
        "Ai stabilit o acțiune pentru context real.",
      ],
      anchorDescription: "Încetinește momentul și vei schimba rezultatul.",
      xp: 0,
      ctaLabel: "Vezi progresul",
    },
    {
      id: "emoflex_short_anchor",
      kind: "ANCHOR",
      shape: "circle",
      title: "Ancora zilei",
      description: "Încetinește momentul și vei schimba rezultatul.",
      xp: 0,
      ctaLabel: "Gata pe azi",
    },
  ],
};
