import type { DailyPathConfig } from "@/types/dailyPath";

export const EMOTIONAL_FLEX_SHORT_EN: DailyPathConfig = {
  id: "emotional_flex_v1_short_en",
  cluster: "emotional_flex_cluster",
  mode: "short",
  lang: "en",
  version: 1,
  skillLabel: "Flexibility: micro-pause before reacting",
  nodes: [
    {
      id: "emoflex_short_intro",
      kind: "INTRO",
      shape: "circle",
      title: "Emotional Flexibility — Quick Session",
      description: "Short, sharp training to help you stay flexible under pressure.",
      xp: 0,
      ctaLabel: "Start training",
    },
    {
      id: "emoflex_short_learn",
      kind: "LEARN",
      shape: "circle",
      title: "The tension → reaction trap",
      description: "Emotions narrow attention. Flexibility expands it before acting.",
      xp: 5,
    },
    {
      id: "emoflex_short_quiz",
      kind: "QUIZ_SINGLE",
      shape: "circle",
      title: "Spot the moment",
      description: "What helps you avoid emotional hijack?",
      quizOptions: [
        { id: "A", label: "Waiting for emotions to fade" },
        { id: "B", label: "Creating 2 seconds of space" },
        { id: "C", label: "Ignoring the feeling" },
      ],
      correctOptionIds: ["B"],
      quizFeedback: {
        correct: "Exactly. The 2-second pause keeps you flexible.",
        incorrect: "Ignoring the feeling leads to a hijack. Create space before you act.",
      },
      xp: 10,
    },
    {
      id: "emoflex_short_sim",
      kind: "SIMULATOR",
      shape: "circle",
      badge: "simulator",
      title: "2-second micro-pause",
      description: "Practice one cycle: Notice → Pause → Exhale. This is your flexibility switch.",
      simulatorConfig: { inhaleSeconds: 2, exhaleSeconds: 2 },
      xp: 10,
      ctaLabel: "Exercise done",
    },
    {
      id: "emoflex_short_real",
      kind: "REAL_WORLD",
      shape: "star",
      badge: "viata_reala",
      title: "Apply in one real context",
      description: "Pick a situation where tension appears and define your 2-second response.",
      fields: [
        {
          id: "context",
          label: "A moment today where I might feel tension…",
          placeholder: "e.g., before the afternoon status meeting",
        },
        {
          id: "rule",
          label: "My action:",
          prefix: "In that moment → I pause 2 seconds and",
          placeholder: "e.g., inhale, name the feeling, then respond intentionally.",
        },
      ],
      xp: 20,
      ctaLabel: "I commit",
    },
    {
      id: "emoflex_short_summary",
      kind: "SUMMARY",
      shape: "circle",
      title: "You trained flexibility today",
      description: "",
      bullets: [
        "You identified emotional tension early.",
        "You practiced the micro-pause.",
        "You set one real-life action.",
      ],
      anchorDescription: "Slow the moment, change the outcome.",
      xp: 0,
      ctaLabel: "View progress",
    },
    {
      id: "emoflex_short_anchor",
      kind: "ANCHOR",
      shape: "circle",
      title: "Daily motto",
      description: "Slow the moment, change the outcome.",
      xp: 0,
      ctaLabel: "Done for today",
    },
  ],
};
