import type { DailyPathConfig } from "@/types/dailyPath";

export const ENERGY_DEEP_RO: DailyPathConfig = {
  id: "focus_energy_v1_deep_ro",
  cluster: "focus_energy_cluster",
  mode: "deep",
  lang: "ro",
  version: 1,
  moduleKey: "energy_recovery",
  skillLabel: "Energie: reset complet",
  autonomyNodeId: "focus_a1",
  nodes: [
    {
      id: "focus_intro",
      kind: "INTRO",
      shape: "circle",
      title: "Energie & recuperare mentală",
      description:
        "Astăzi lucrezi la bateria ta mentală. Vezi unde se scurge energia în timpul zilei și înveți un mic reflex de reset care îți protejează claritatea când schimbi activitatea.",
      xp: 0,
      ctaLabel: "Încep",
    },
    {
      id: "focus_example1",
      kind: "LEARN",
      shape: "circle",
      title: "O zi care golește bateria",
      description:
        "Andrei își începe ziua hotărât: vrea să termine un raport.\nDar sare între email, WhatsApp, banking, apeluri și tab-uri noi.\nSeara e obosit și raportul e abia început.\nNu munca l-a obosit, ci schimbările haotice de context.",
      xp: 5,
    },
    {
      id: "focus_l1",
      kind: "LEARN",
      shape: "circle",
      title: "Ce este energia mentală?",
      description:
        "Imaginează-ți că ai o baterie invizibilă pentru atenție și decizii. Nu obosești doar pentru că muncești mult, ci pentru că această baterie se golește de fiecare dată când ești întrerupt, sari de la un lucru la altul sau ții prea multe lucruri în minte.\nEnergie mentală = capacitatea ta de a fi prezent, lucid și orientat în ce faci acum.",
      xp: 5,
    },
    {
      id: "focus_quiz1",
      kind: "QUIZ_SINGLE",
      shape: "circle",
      title: "Test rapid",
      description: "Ce îți golește cel mai tare energia mentală?",
      quizOptions: [
        { id: "A", label: "Trei ore de lucru concentrat cu pauze scurte." },
        { id: "B", label: "Să sari de zeci de ori între email, chat, telefon." },
        { id: "C", label: "O plimbare de 30 de minute fără telefon." },
      ],
      correctOptionIds: ["B"],
      quizFeedback: {
        correct: "Exact. Comutările dese tocmai asta fac.",
        incorrect: "Aproape. Lucrul concentrat protejează energia. Schimbările dese o scurg.",
      },
      xp: 10,
    },
    {
      id: "focus_l2",
      kind: "LEARN",
      shape: "circle",
      title: "De ce te rupe schimbul de context",
      description:
        "Când treci la altceva, mintea are nevoie să „mute scena”:\n– să uite ce făcea,\n– să încarce noul context.\nDacă faci asta de 50–100 ori/zi, energia cade masiv.\nReflexul care ajută: pauza de 2 secunde.",
      xp: 5,
    },
    {
      id: "focus_quiz2",
      kind: "QUIZ_SINGLE",
      shape: "circle",
      title: "Aplicare",
      description: "Ești la laptop și treci la alt task. Ce protejează cel mai bine energia ta?",
      quizOptions: [
        { id: "A", label: "Deschid imediat alt tab și intru pe social media." },
        { id: "B", label: "Mă opresc 2 secunde → inspir 2 sec, expir 2 sec → apoi încep." },
        { id: "C", label: "Deschid 3 tab-uri ca să aleg după chef." },
      ],
      correctOptionIds: ["B"],
      quizFeedback: {
        correct: "Da. Pauza de 2 secunde îți protejează energia.",
        incorrect: "Aproape. Mintea are nevoie de un spațiu gol între activități.",
      },
      xp: 10,
    },
    {
      id: "focus_sim1",
      kind: "SIMULATOR",
      shape: "circle",
      badge: "simulator",
      title: "Simulator: pauza ta de 2 secunde",
      description:
        "Antrenezi reflexul de reset. Când cercul se umple: inspiră 2 secunde. Când se golește: expiră 2 secunde. Repetă 2–3 cicluri.",
      xp: 15,
      simulatorConfig: { inhaleSeconds: 2, exhaleSeconds: 2 },
      ctaLabel: "Am făcut exercițiul",
    },
    {
      id: "focus_a1",
      kind: "ACTION",
      shape: "star",
      title: "Cum simți după primele încercări?",
      description: "Mai vrei o rundă de antrenament sau ești pregătit pentru provocare?",
      xp: 0,
    },
    {
      id: "focus_sim2",
      kind: "SIMULATOR",
      shape: "hollow",
      badge: "simulator",
      softPathOnly: true,
      title: "Extra training",
      description: "Încă 2–3 cicluri de pauză 2–2 îți consolidează reflexul.",
      xp: 5,
      simulatorConfig: { inhaleSeconds: 2, exhaleSeconds: 2 },
      ctaLabel: "Am făcut exercițiul",
    },
    {
      id: "energy_context_learn",
      kind: "LEARN",
      shape: "circle",
      title: "Ce înseamnă să schimbi contextul",
      description:
        "Schimbarea de context apare când treci de la telefon la laptop, de la email la call etc.\nDacă intri în noua sarcină pe pilot automat, energia se scurge.\nReflexul tău nou: pauză conștientă de 2 secunde.",
      xp: 0,
    },
    {
      id: "focus_real1",
      kind: "REAL_WORLD",
      shape: "star",
      badge: "viata_reala",
      title: "Provocarea ta reală de azi",
      description: "Scrie contextul și regula ta personalizată.",
      fields: [
        {
          id: "context",
          label: "Azi, când te întâlnești cu o situație precum:",
          placeholder: "ex: închid telefonul și mă apuc de lucru la laptop",
        },
        {
          id: "rule",
          label: "Regula mea de azi:",
          prefix: "Când",
          suffix: "→ respir 2 secunde înainte să continui.",
          placeholder: "ex: deschid laptopul și mă apuc de lucru",
        },
      ],
      xp: 25,
      ctaLabel: "Îmi iau angajamentul",
    },
    {
      id: "focus_summary",
      kind: "SUMMARY",
      shape: "circle",
      title: "Felicitări, ai terminat antrenamentul de azi.",
      description: "",
      bullets: [
        "Schimbările dese de context consumă masiv energia.",
        "Pauza de 2 secunde protejează mintea între task-uri.",
        "Legarea regulii de un context real crește șansa să o aplici.",
      ],
      anchorDescription: "Când schimb contextul, respir 2 secunde.",
      xp: 0,
      ctaLabel: "Vezi progresul tău",
    },
    {
      id: "focus_anchor",
      kind: "ANCHOR",
      shape: "circle",
      title: "Ancora zilei",
      description: "Când schimb contextul, respir 2 secunde.",
      xp: 0,
      ctaLabel: "Gata pe azi",
    },
  ],
};
