import type { DailyPathConfig } from "@/types/dailyPath";

export const ENERGY_DEEP_EN: DailyPathConfig = {
  id: "focus_energy_v1_deep_en",
  cluster: "focus_energy_cluster",
  mode: "deep",
  lang: "en",
  version: 1,
  moduleKey: "energy_recovery",
  skillLabel: "Energy: full reset",
  autonomyNodeId: "focus_a1",
  nodes: [
    {
      id: "focus_intro",
      kind: "INTRO",
      shape: "circle",
      title: "Mental Energy & Recovery",
      description:
        "Today you’ll work on your mental battery. You’ll see where energy leaks throughout the day and learn a simple 2-second reset that protects your clarity whenever you switch tasks.",
      xp: 0,
      ctaLabel: "Start training",
    },
    {
      id: "focus_example1",
      kind: "LEARN",
      shape: "circle",
      title: "A day that drains your battery",
      description:
        "Andrei starts the day motivated: he wants to finish an important report.\nBut he bounces between email, WhatsApp, banking apps, calls, and new tabs.\nAt night, he's exhausted and the report is barely started.\nHe wasn’t worn out by “work,” but by chaotic context switching.",
      xp: 5,
    },
    {
      id: "focus_l1",
      kind: "LEARN",
      shape: "circle",
      title: "What is mental energy?",
      description:
        "Imagine a hidden battery for attention and decisions.\nYou don’t get mentally tired just because you work a lot — your battery drains every time you are interrupted, jump between tasks, or hold too many things in mind at once.\nMental energy = your capacity to stay present, clear, and intentional.",
      xp: 5,
    },
    {
      id: "focus_quiz1",
      kind: "QUIZ_SINGLE",
      shape: "circle",
      title: "Quick check",
      description: "Which situation drains your mental energy the most?",
      quizOptions: [
        { id: "A", label: "Three hours of focused work with short breaks." },
        { id: "B", label: "Jumping dozens of times between email, chat, and notifications." },
        { id: "C", label: "A 30-minute walk without your phone." },
      ],
      correctOptionIds: ["B"],
      quizFeedback: {
        correct: "Correct. Rapid context switching is the biggest hidden drain.",
        incorrect: "Not quite. Focused work protects energy. Constant switching drains it.",
      },
      xp: 10,
    },
    {
      id: "focus_l2",
      kind: "LEARN",
      shape: "circle",
      title: "Why context switching breaks you",
      description:
        "Every time you shift tasks, your mind needs to “move the scene”:\n– release what you were doing,\n– load what matters now.\nDo this 50–100 times a day and your energy collapses.\nThe solution: a simple 2-second pause.",
      xp: 5,
    },
    {
      id: "focus_quiz2",
      kind: "QUIZ_SINGLE",
      shape: "circle",
      title: "Apply the rule",
      description: "You finish a task and want to start the next one. What protects your energy best?",
      quizOptions: [
        { id: "A", label: "Open a new tab and check social media for 1–2 minutes." },
        { id: "B", label: "Pause for 2 seconds → inhale 2 sec, exhale 2 sec → then start intentionally." },
        { id: "C", label: "Open three tabs in parallel and decide based on impulse." },
      ],
      correctOptionIds: ["B"],
      quizFeedback: {
        correct: "Exactly. The 2-second pause resets your mental state.",
        incorrect: "Almost. Your mind needs a small blank space before the next task.",
      },
      xp: 10,
    },
    {
      id: "focus_sim1",
      kind: "SIMULATOR",
      shape: "circle",
      badge: "simulator",
      title: "Simulator: Your 2-second pause",
      description:
        "Train the reset reflex. When the circle fills: inhale for 2 seconds. When it empties: exhale for 2 seconds. Repeat 2–3 cycles.",
      xp: 15,
      simulatorConfig: { inhaleSeconds: 2, exhaleSeconds: 2 },
      ctaLabel: "Exercise done",
    },
    {
      id: "focus_a1",
      kind: "ACTION",
      shape: "star",
      title: "How do you feel after the first rounds?",
      description: "Choose your next step.",
      xp: 0,
    },
    {
      id: "focus_sim2",
      kind: "SIMULATOR",
      shape: "hollow",
      badge: "simulator",
      softPathOnly: true,
      title: "Extra training",
      description: "Another 2–3 cycles strengthen the reflex.",
      xp: 5,
      simulatorConfig: { inhaleSeconds: 2, exhaleSeconds: 2 },
      ctaLabel: "Exercise done",
    },
    {
      id: "energy_context_learn",
      kind: "LEARN",
      shape: "circle",
      title: "What “context switching” actually is",
      description:
        "Context switching is not abstract. It happens whenever you:\n– move from phone to laptop,\n– end a call and dive into emails,\n– leave a meeting and open a new document.\nEntering the next activity on autopilot drains energy.\nYour new reflex: a conscious 2-second pause.",
      xp: 0,
    },
    {
      id: "focus_real1",
      kind: "REAL_WORLD",
      shape: "star",
      badge: "viata_reala",
      title: "Your real challenge for today",
      description: "Write your personal rule for today.",
      fields: [
        {
          id: "context",
          label: "Today, when I encounter a situation like:",
          placeholder: "e.g., I put down my phone and start work",
        },
        {
          id: "rule",
          label: "My rule for today:",
          prefix: "When",
          suffix: "→ I pause and breathe for 2 seconds before continuing.",
          placeholder: "e.g., I close my phone and open my laptop with intention",
        },
      ],
      xp: 25,
      ctaLabel: "I commit",
    },
    {
      id: "focus_summary",
      kind: "SUMMARY",
      shape: "circle",
      title: "Great job — today’s training is complete.",
      description: "",
      bullets: [
        "Frequent context switches drain energy fast.",
        "A 2-second pause protects clarity between tasks.",
        "Writing a personal rule increases the chance you'll apply it.",
      ],
      anchorDescription: "When I switch context, I pause for 2 seconds.",
      xp: 0,
      ctaLabel: "See your progress",
    },
    {
      id: "focus_anchor",
      kind: "ANCHOR",
      shape: "circle",
      title: "Daily motto",
      description: "When I switch context, I pause for 2 seconds.",
      xp: 0,
      ctaLabel: "Done for today",
    },
  ],
};
