import type { AdaptiveCluster, DailyPathConfig } from "@/types/dailyPath";

export const DAILY_PATHS: DailyPathConfig[] = [
  {
    cluster: "clarity_cluster",
    autonomyNodeId: "clarity_a1",
    nodes: [
      {
        id: "clarity_l1",
        kind: "LEARN",
        shape: "circle",
        title: "Ce înseamnă claritatea?",
        description: "Un exemplu simplu de problemă vagă vs problemă clară.",
        xp: 10,
        linkType: "kuno",
        linkTarget: "clarity_intro",
      },
      {
        id: "clarity_l2",
        kind: "LEARN",
        shape: "circle",
        title: "Regula celor 7 cuvinte",
        description: "Cum să reduci o idee la maximum 7 cuvinte.",
        xp: 10,
        linkType: "kuno",
        linkTarget: "clarity_7_words",
      },
      {
        id: "clarity_a1",
        kind: "ACTION",
        shape: "star",
        title: "Aplică regula în viața ta",
        description: "Alege un lucru important azi și exprimă-l în 7 cuvinte.",
        xp: 25,
        linkType: "abil",
        linkTarget: "clarity_daily_action",
      },
      {
        id: "clarity_l3",
        kind: "LEARN",
        shape: "hollow",
        title: "Exemple: claritate vs ambiguitate",
        description: "Două exemple de propoziții clare și neclare.",
        xp: 5,
        softPathOnly: true,
        linkType: "kuno",
        linkTarget: "clarity_examples",
      },
      {
        id: "clarity_a2",
        kind: "ACTION",
        shape: "star",
        title: "Încă o idee în 7 cuvinte",
        description: "Formulează încă o idee importantă în 7 cuvinte.",
        xp: 20,
        isBonus: true,
        linkType: "abil",
        linkTarget: "clarity_bonus_action",
      },
    ],
  },
  {
    cluster: "emotional_flex_cluster",
    autonomyNodeId: "emoflex_a1",
    nodes: [
      {
        id: "emoflex_l1",
        kind: "LEARN",
        shape: "circle",
        title: "Ce este reacția automată?",
        description: "Trigger → tensiune → reacție reflexă.",
        xp: 10,
        linkType: "kuno",
        linkTarget: "emoflex_reaction_intro",
      },
      {
        id: "emoflex_r1",
        kind: "RESET",
        shape: "circle",
        title: "Reset de 2 secunde",
        description: "Un micro-reset respirator când apare tensiune.",
        xp: 10,
        linkType: "none",
      },
      {
        id: "emoflex_a1",
        kind: "ACTION",
        shape: "star",
        title: "Aplică resetul azi",
        description: "Dacă apare tensiune, folosește pauza de 2 secunde.",
        xp: 25,
        linkType: "abil",
        linkTarget: "emoflex_reset_action",
      },
      {
        id: "emoflex_l3",
        kind: "LEARN",
        shape: "hollow",
        title: "Reacție imatură vs reacție matură",
        description: "Un exemplu de răspuns impulsiv vs răspuns conștient.",
        xp: 5,
        softPathOnly: true,
        linkType: "kuno",
        linkTarget: "emoflex_example",
      },
      {
        id: "emoflex_a2",
        kind: "ACTION",
        shape: "star",
        title: "Exersează reacția matură mental",
        description: "Simulează un scenariu mental și alege răspunsul matur.",
        xp: 20,
        isBonus: true,
        linkType: "abil",
        linkTarget: "emoflex_bonus_action",
      },
    ],
  },
  {
    cluster: "focus_energy_cluster",
    autonomyNodeId: "focus_a1",
    nodes: [
      {
        id: "focus_l1",
        kind: "LEARN",
        shape: "circle",
        title: "Ce este monotaskingul?",
        description: "De ce e mai eficient să faci un singur lucru odată.",
        xp: 10,
        linkType: "kuno",
        linkTarget: "focus_monotask_intro",
      },
      {
        id: "focus_r1",
        kind: "RESET",
        shape: "circle",
        title: "Respiră 3–4 secunde",
        description: "Un reset scurt de focus prin respirație ghidată.",
        xp: 10,
        linkType: "none",
      },
      {
        id: "focus_a1",
        kind: "ACTION",
        shape: "star",
        title: "2 minute fără telefon azi",
        description: "Alege un moment de 2 minute fără telefon.",
        xp: 25,
        linkType: "abil",
        linkTarget: "focus_2min_action",
      },
      {
        id: "focus_l3",
        kind: "LEARN",
        shape: "hollow",
        title: "De ce 2 minute contează?",
        description: "Metaforă simplă: cum 2 minute îți schimbă ritmul mental.",
        xp: 5,
        softPathOnly: true,
        linkType: "kuno",
        linkTarget: "focus_2min_explained",
      },
      {
        id: "focus_a2",
        kind: "ACTION",
        shape: "star",
        title: "Încă un moment de 2 minute",
        description: "Găsește încă un moment scurt fără telefon azi.",
        xp: 20,
        isBonus: true,
        linkType: "abil",
        linkTarget: "focus_bonus_action",
      },
    ],
  },
];

export function getDailyPathForCluster(cluster: AdaptiveCluster): DailyPathConfig | null {
  return DAILY_PATHS.find((path) => path.cluster === cluster) ?? null;
}
