import type { AdaptiveCluster, DailyPathConfig } from "@/types/dailyPath";

export const DAILY_PATHS: DailyPathConfig[] = [
  {
    cluster: "clarity_cluster",
    autonomyNodeId: "clarity_a1",
    nodes: [
      {
        id: "clarity_l1",
        kind: "LEARN",
        shape: "circle",
        title: "Claritate mentală",
        description:
          "Diferența dintre o zi cu gânduri împrăștiate și una în care știi exact care e următorul pas.",
        xp: 10,
        linkType: "kuno",
        linkTarget: "clarity_intro",
      },
      {
        id: "clarity_l2",
        kind: "LEARN",
        shape: "circle",
        title: "Regula celor 7 cuvinte",
        description: "Când poți descrie o problemă în 7 cuvinte, creierul tău știe exact ce are de făcut.",
        xp: 10,
        linkType: "kuno",
        linkTarget: "clarity_7_words",
      },
      {
        id: "clarity_a1",
        kind: "ACTION",
        shape: "star",
        title: "Prioritatea zilei în 7 cuvinte",
        description: "Alege cel mai important lucru de azi și formulează-l în 7 cuvinte clare.",
        xp: 25,
        linkType: "abil",
        linkTarget: "clarity_daily_action",
      },
      {
        id: "clarity_l3",
        kind: "LEARN",
        shape: "hollow",
        title: "Fraze confuze vs. fraze clare",
        description:
          "Vezi două exemple: cum sună o frază care creează ceață și cum sună una care deschide drumul.",
        xp: 5,
        softPathOnly: true,
        linkType: "kuno",
        linkTarget: "clarity_examples",
      },
      {
        id: "clarity_a2",
        kind: "ACTION",
        shape: "star",
        title: "Încă un lucru, încă 7 cuvinte",
        description:
          "Alege un al doilea lucru important și scrie-l din nou în 7 cuvinte. Îți întărești „mușchiul” clarității.",
        xp: 20,
        isBonus: true,
        linkType: "abil",
        linkTarget: "clarity_bonus_action",
      },
    ],
  },
  {
    cluster: "emotional_flex_cluster",
    autonomyNodeId: "emoflex_a1",
    nodes: [
      {
        id: "emoflex_l1",
        kind: "LEARN",
        shape: "circle",
        title: "Reacție automată vs răspuns ales",
        description: "Stresul apasă butoane vechi. Flexibilitatea înseamnă să vezi butonul și să alegi alt răspuns.",
        xp: 10,
        linkType: "kuno",
        linkTarget: "emoflex_reaction_intro",
      },
      {
        id: "emoflex_r1",
        kind: "RESET",
        shape: "circle",
        title: "Reset de 2 secunde",
        description: "O pauză scurtă între stimul și răspuns îți dă înapoi controlul asupra comportamentului.",
        xp: 10,
        linkType: "none",
      },
      {
        id: "emoflex_a1",
        kind: "ACTION",
        shape: "star",
        title: "Aplică resetul în prima tensiune de azi",
        description: "La primul moment de tensiune de azi, inspiră adânc, numără 2 secunde și abia apoi răspunde.",
        xp: 25,
        linkType: "abil",
        linkTarget: "emoflex_reset_action",
      },
      {
        id: "emoflex_l3",
        kind: "LEARN",
        shape: "hollow",
        title: "Cum arată un răspuns matur",
        description: "Un exemplu simplu: aceeași situație, dar două comportamente complet diferite.",
        xp: 5,
        softPathOnly: true,
        linkType: "kuno",
        linkTarget: "emoflex_example",
      },
      {
        id: "emoflex_a2",
        kind: "ACTION",
        shape: "star",
        title: "Rescrie scena în minte",
        description: "Gândește-te la o tensiune recentă și imaginează-ți cum ar fi arătat un răspuns mai calm și mai clar.",
        xp: 20,
        isBonus: true,
        linkType: "abil",
        linkTarget: "emoflex_bonus_action",
      },
    ],
  },
  {
    cluster: "focus_energy_cluster",
    autonomyNodeId: "focus_a1",
    nodes: [
      {
        id: "focus_intro",
        kind: "INTRO",
        shape: "circle",
        title: "Ce este focusul calm",
        description: "Înveți cum 2 minute de liniște îți pot reseta energia mentală înainte de o zi aglomerată.",
        xp: 0,
        linkType: "none",
      },
      {
        id: "focus_l1",
        kind: "LEARN",
        shape: "circle",
        title: "Un singur lucru odată",
        description: "Monotaskingul reduce „zgomotul” mental și eliberează energie pentru ce e important.",
        xp: 10,
        linkType: "kuno",
        linkTarget: "focus_monotask_intro",
      },
      {
        id: "focus_example1",
        kind: "LEARN",
        shape: "circle",
        title: "Două scenarii simple",
        description: "Cum arată o minte împrăștiată vs o minte care știe exact ce urmează.",
        xp: 8,
        linkType: "kuno",
        linkTarget: "focus_example_intro",
      },
      {
        id: "focus_quiz1",
        kind: "QUIZ_SINGLE",
        shape: "circle",
        title: "Ce scenariu e mai clar?",
        description: "Alege situația în care focusul e păstrat corect.",
        xp: 8,
        quizOptions: [
          { id: "a", label: "Sari între emailuri și mesaje în timp ce scrii." },
          { id: "b", label: "Blochezi 5 minute doar pentru răspunsul critic." },
        ],
        correctOptionIds: ["b"],
      },
      {
        id: "focus_l2",
        kind: "LEARN",
        shape: "circle",
        title: "Reset = energie",
        description: "O pauză scurtă repornește cortexul frontal și îți dă înapoi controlul.",
        xp: 8,
        linkType: "kuno",
        linkTarget: "focus_reset_intro",
      },
      {
        id: "focus_quiz2",
        kind: "QUIZ_SINGLE",
        shape: "circle",
        title: "Ce reset alegi?",
        description: "Alege resetul care îți reface energia mentală în < 60 de secunde.",
        xp: 8,
        quizOptions: [
          { id: "a", label: "Scrollezi 2 minute pe social media." },
          { id: "b", label: "Închizi ochii și respiri 3-4 secunde pe expir." },
        ],
        correctOptionIds: ["b"],
      },
      {
        id: "focus_sim1",
        kind: "SIMULATOR",
        shape: "circle",
        title: "Simulator: respiră 3–4 secunde",
        description: "Închide ochii și sincronizează-ți respirația: inspir 3 secunde, expir 4 secunde, de 3 ori.",
        xp: 12,
        badge: "simulator",
        linkType: "none",
      },
      {
        id: "focus_a1",
        kind: "ACTION",
        shape: "star",
        title: "2 minute fără telefon azi",
        description: "Alege un moment concret al zilei pentru cele 2 minute fără telefon. Ești pregătit sau mai exersezi?",
        xp: 25,
        linkType: "abil",
        linkTarget: "focus_2min_action",
      },
      {
        id: "focus_sim2",
        kind: "SIMULATOR",
        shape: "hollow",
        title: "Simulator: repetă exercițiul",
        description: "Încă un ciclu ghidat de respirație pentru a fixa reflexul. Focus respiră = focus aplică.",
        xp: 12,
        badge: "simulator",
        softPathOnly: true,
        linkType: "none",
      },
      {
        id: "focus_real1",
        kind: "REAL_WORLD",
        shape: "star",
        title: "Aplică în viața reală",
        description: "Alege tot azi o situație reală în care vei folosi cele 2 minute fără telefon înainte de a continua.",
        xp: 30,
        badge: "viata_reala",
        linkType: "none",
      },
      {
        id: "focus_summary",
        kind: "SUMMARY",
        shape: "circle",
        title: "Ce ai fixat azi",
        description: "Un singur lucru odată • Reset de 3–4 secunde • 2 minute fără telefon = energie pentru ce contează.",
        xp: 5,
        linkType: "none",
      },
      {
        id: "focus_anchor",
        kind: "ANCHOR",
        shape: "circle",
        title: "Motto-ul zilei",
        description: "Două minute investite în claritate îți dau înapoi o oră întreagă mai târziu.",
        xp: 5,
        linkType: "none",
      },
    ],
  },
];

export function getDailyPathForCluster(cluster: AdaptiveCluster): DailyPathConfig | null {
  return DAILY_PATHS.find((path) => path.cluster === cluster) ?? null;
}
