import type { AdaptiveCluster, DailyPathConfig } from "@/types/dailyPath";

export const DAILY_PATHS: DailyPathConfig[] = [
  {
    cluster: "focus_energy_cluster",
    autonomyNodeId: "focus_a1",
    nodes: [
      {
        id: "focus_intro",
        kind: "INTRO",
        shape: "circle",
        title: "Energia minții",
        description:
          "Epuizarea mentală nu vine din lucrurile grele, ci din lipsa recuperării. Azi înveți metoda celor 4–90 secunde.",
        xp: 0,
      },
      {
        id: "focus_example1",
        kind: "LEARN",
        shape: "circle",
        title: "Semnalul oboselii mentale",
        description:
          "Deschizi telefonul pentru ceva anume, iar după 40 de secunde ești în altă aplicație. Nu e lipsa voinței — e oboseală neuronală.",
        xp: 5,
      },
      {
        id: "focus_l1",
        kind: "LEARN",
        shape: "circle",
        title: "Regula celor 90 de secunde",
        description:
          "O pauză deliberată de 60–90 de secunde reduce tensiunea corticală și crește energia mentală cu 10–15%.",
        xp: 5,
      },
      {
        id: "focus_quiz1",
        kind: "QUIZ_SINGLE",
        shape: "circle",
        title: "Test rapid",
        description: "Ce ajută cel mai mult recuperarea mentală?",
        quizOptions: [
          { id: "A", label: "O pauză scurtă, intenționată" },
          { id: "B", label: "Încă un scroll rapid" },
          { id: "C", label: "Încă două aplicații deschise" },
        ],
        correctOptionIds: ["A"],
        xp: 10,
      },
      {
        id: "focus_l2",
        kind: "LEARN",
        shape: "circle",
        title: "Zgomotul mental",
        description: "Zgomotul mental apare când sari între sarcini. Micro-recuperarea aduce mintea înapoi pe un singur fir.",
        xp: 5,
      },
      {
        id: "focus_quiz2",
        kind: "QUIZ_SINGLE",
        shape: "circle",
        title: "Ce ai face?",
        description: "Ai un task important. Primești o notificare. Ce păstrează energia ta?",
        quizOptions: [
          { id: "A", label: "Deschid notificarea imediat" },
          { id: "B", label: "Respir 4 secunde și decid" },
          { id: "C", label: "Ignor notificările toată ziua" },
        ],
        correctOptionIds: ["B"],
        xp: 10,
      },
      {
        id: "focus_sim1",
        kind: "SIMULATOR",
        shape: "circle",
        badge: "simulator",
        title: "Simulator: Reset 4–4",
        description: "Inspiră 4 secunde… expiră 4 secunde. Mintea învață un nou reflex energetic.",
        xp: 15,
        simulatorConfig: { inhaleSeconds: 4, exhaleSeconds: 4 },
      },
      {
        id: "focus_a1",
        kind: "ACTION",
        shape: "star",
        title: "Autonomie",
        description: "Mai vrei o rundă de antrenament sau ești pregătit pentru viața reală?",
        xp: 0,
      },
      {
        id: "focus_sim2",
        kind: "SIMULATOR",
        shape: "hollow",
        badge: "simulator",
        softPathOnly: true,
        title: "Extra training",
        description: "Încă 30 sec de reset. Construiești stabilitate energetică.",
        xp: 5,
        simulatorConfig: { inhaleSeconds: 4, exhaleSeconds: 4 },
      },
      {
        id: "energy_context_learn",
        kind: "LEARN",
        shape: "circle",
        title: "Ce înseamnă schimbul de context",
        description:
          "Treci de la telefon → lucru, de la lucru → pauză, de la pauză → email, de la un task → alt task. Ori de câte ori schimbi universul mental, poți pierde energie dacă intri impulsiv.",
        xp: 0,
      },
      {
        id: "focus_real1",
        kind: "REAL_WORLD",
        shape: "star",
        badge: "viata_reala",
        title: "Viața reală",
        description:
          "Azi, când schimbi contextul (telefon → task), respiră 4 secunde înainte. Regula: „Când schimb contextul → respir 4 sec.”",
        xp: 25,
      },
      {
        id: "focus_summary",
        kind: "SUMMARY",
        shape: "circle",
        title: "Azi ai învățat",
        description: "1) Energia mentală se reface în 60–90 sec.\n2) Resetul 4–4 reduce tensiunea.\n3) Când schimbi contextul → respiră.",
        xp: 0,
      },
      {
        id: "focus_anchor",
        kind: "ANCHOR",
        shape: "circle",
        title: "Ancora zilei",
        description: "Energia se construiește în pauze, nu în efort.",
        xp: 0,
      },
    ],
  },
  {
    cluster: "clarity_cluster",
    autonomyNodeId: "clarity_a1",
    nodes: [
      {
        id: "clarity_intro",
        kind: "INTRO",
        shape: "circle",
        title: "Claritate în 7 cuvinte",
        description: "Mintea confuză creează probleme imaginare. Azi înveți regula celor 7 cuvinte.",
        xp: 0,
      },
      {
        id: "clarity_example1",
        kind: "LEARN",
        shape: "circle",
        title: "Când nu știi ce faci de fapt",
        description: "Deschizi laptopul, dar nu știi de unde să începi. Confuzia consumă energie cognitivă.",
        xp: 5,
      },
      {
        id: "clarity_l1",
        kind: "LEARN",
        shape: "circle",
        title: "Regula celor 7 cuvinte",
        description: "Dacă nu poți formula sarcina în 7 cuvinte, mintea ta nu știe ce are de făcut.",
        xp: 10,
      },
      {
        id: "clarity_quiz1",
        kind: "QUIZ_SINGLE",
        shape: "circle",
        title: "Care e clară?",
        description: "Alege propoziția cu claritatea cea mai mare:",
        quizOptions: [
          { id: "A", label: "Trebuie să rezolv multe azi..." },
          { id: "B", label: "Trimit raportul final la Andrei" },
          { id: "C", label: "Mă pun pe treabă cât pot" },
        ],
        correctOptionIds: ["B"],
        xp: 10,
      },
      {
        id: "clarity_l2",
        kind: "LEARN",
        shape: "circle",
        title: "Ceața cognitivă",
        description: "Confuzia este o tensiune. Claritatea este relaxare. Creierul iubește instrucțiunile simple.",
        xp: 5,
      },
      {
        id: "clarity_quiz2",
        kind: "QUIZ_SINGLE",
        shape: "circle",
        title: "Aplicare",
        description: "Ce faci când simți confuzie?",
        quizOptions: [
          { id: "A", label: "Scriu în 7 cuvinte ce am de făcut" },
          { id: "B", label: "Deschid o aplicație random" },
          { id: "C", label: "Aștept să îmi treacă" },
        ],
        correctOptionIds: ["A"],
        xp: 10,
      },
      {
        id: "clarity_sim1",
        kind: "SIMULATOR",
        shape: "circle",
        badge: "simulator",
        title: "Simulator: 7 cuvinte",
        description: "Formulează în 7 cuvinte exact ce faci în următoarele 2 minute.",
        xp: 15,
      },
      {
        id: "clarity_a1",
        kind: "ACTION",
        shape: "star",
        title: "Autonomie",
        description: "Mai vrei o simulare sau treci direct la viața reală?",
        xp: 0,
      },
      {
        id: "clarity_sim2",
        kind: "SIMULATOR",
        shape: "hollow",
        badge: "simulator",
        softPathOnly: true,
        title: "Simulator extra",
        description: "Scrie încă o sarcină în 7 cuvinte. Claritatea se construiește prin repetare.",
        xp: 5,
      },
      {
        id: "clarity_real1",
        kind: "REAL_WORLD",
        shape: "star",
        badge: "viata_reala",
        title: "Viața reală",
        description: "Azi, orice sarcină începi, pune-o în 7 cuvinte înainte. *Când încep → formulez în 7 cuvinte.*",
        xp: 25,
      },
      {
        id: "clarity_summary",
        kind: "SUMMARY",
        shape: "circle",
        title: "Azi ai învățat",
        description: "1) Confuzia consumă energie.\n2) Claritatea începe cu 7 cuvinte.\n3) Formula scurtă reduce tensiunea mentală.",
        xp: 0,
      },
      {
        id: "clarity_anchor",
        kind: "ANCHOR",
        shape: "circle",
        title: "Ancora zilei",
        description: "Mintea clară creează drum, nu zid.",
        xp: 0,
      },
    ],
  },
  {
    cluster: "emotional_flex_cluster",
    autonomyNodeId: "emoflex_a1",
    nodes: [
      {
        id: "emoflex_intro",
        kind: "INTRO",
        shape: "circle",
        title: "Flexibilitate emoțională",
        description: "Reacția automată te conduce. Răspunsul ales te eliberează. Azi înveți pauza de 2 secunde.",
        xp: 0,
      },
      {
        id: "emoflex_example1",
        kind: "LEARN",
        shape: "circle",
        title: "Când explodezi prea repede",
        description: "Primești un mesaj tensionat și simți impulsul să răspunzi imediat. Aceasta e reacție automată.",
        xp: 5,
      },
      {
        id: "emoflex_l1",
        kind: "LEARN",
        shape: "circle",
        title: "Regula de 2 secunde",
        description: "Între stimul și răspuns există libertatea ta. O pauză de 2 secunde resetează impulsul.",
        xp: 10,
      },
      {
        id: "emoflex_quiz1",
        kind: "QUIZ_SINGLE",
        shape: "circle",
        title: "Recunoaște",
        description: "Ce este reacția automată?",
        quizOptions: [
          { id: "A", label: "Răspuns impulsiv, imediat" },
          { id: "B", label: "Răspuns calculat" },
          { id: "C", label: "Lipsa emoțiilor" },
        ],
        correctOptionIds: ["A"],
        xp: 10,
      },
      {
        id: "emoflex_l2",
        kind: "LEARN",
        shape: "circle",
        title: "Cum recâștigi controlul",
        description: "Flexibilitatea emoțională nu înseamnă să nu simți — ci să ai timp să alegi ce faci cu ceea ce simți.",
        xp: 5,
      },
      {
        id: "emoflex_quiz2",
        kind: "QUIZ_SINGLE",
        shape: "circle",
        title: "Tu ce alegi?",
        description: "Primești o critică nedreaptă. Care e răspunsul folosind flexibilitatea emoțională?",
        quizOptions: [
          { id: "A", label: "Explodez imediat" },
          { id: "B", label: "Inspir 2 secunde și răspund calm" },
          { id: "C", label: "Ignor persoana complet" },
        ],
        correctOptionIds: ["B"],
        xp: 10,
      },
      {
        id: "emoflex_sim1",
        kind: "SIMULATOR",
        shape: "circle",
        badge: "simulator",
        title: "Simulator: Pauza de 2 secunde",
        description: "Pauza de 2 secunde. Încetinești ritmul mental și reduci agitația din tranzițiile dintre activități. Inspiră 2 secunde… expiră 2 secunde.",
        xp: 15,
        simulatorConfig: { inhaleSeconds: 2, exhaleSeconds: 2 },
      },
      {
        id: "emoflex_a1",
        kind: "ACTION",
        shape: "star",
        title: "Autonomie",
        description: "Vrei încă o simulare sau aplici direct în viața reală?",
        xp: 0,
      },
      {
        id: "emoflex_sim2",
        kind: "SIMULATOR",
        shape: "hollow",
        badge: "simulator",
        softPathOnly: true,
        title: "Simulator extra",
        description: "Pauza de 2 secunde. Încetinești ritmul mental și reduci agitația din tranzițiile dintre activități. Inspiră 2 secunde… expiră 2 secunde.",
        xp: 5,
        simulatorConfig: { inhaleSeconds: 2, exhaleSeconds: 2 },
      },
      {
        id: "emoflex_real1",
        kind: "REAL_WORLD",
        shape: "star",
        badge: "viata_reala",
        title: "Viața reală",
        description:
          "Azi, la primul trigger, inspiră 2 secunde înainte să răspunzi. Regula: *Când apare tensiunea → fac pauza.*",
        xp: 25,
      },
      {
        id: "emoflex_summary",
        kind: "SUMMARY",
        shape: "circle",
        title: "Azi ai învățat",
        description:
          "1) Între stimul și răspuns e libertatea ta.\n2) Pauza de 2 secunde îți protejează relațiile.\n3) Flexibilitatea = răspuns, nu reacție.",
        xp: 0,
      },
      {
        id: "emoflex_anchor",
        kind: "ANCHOR",
        shape: "circle",
        title: "Ancora zilei",
        description: "Tăria nu e reacția. Tăria e alegerea.",
        xp: 0,
      },
    ],
  },
];

export const DAILY_PATHS_SHORT: Record<AdaptiveCluster, DailyPathConfig> = {
  focus_energy_cluster: {
    cluster: "focus_energy_cluster",
    nodes: [
      {
        id: "focus_short_intro",
        kind: "INTRO",
        shape: "circle",
        title: "Focus & energie",
        description: "Două minute fără telefon pot reseta o zi încărcată.",
        xp: 0,
      },
      {
        id: "focus_short_learn",
        kind: "LEARN",
        shape: "circle",
        title: "Resetul de 2 minute",
        description: "Monotasking + respirație scurtă = energie pentru ce contează.",
        xp: 5,
      },
      {
        id: "focus_short_sim",
        kind: "SIMULATOR",
        shape: "circle",
        badge: "simulator",
        title: "Simulator",
        description: "Inspir 4 secunde, expir 4 secunde. Repet de 2 ori.",
        xp: 10,
        simulatorConfig: { inhaleSeconds: 4, exhaleSeconds: 4 },
      },
      {
        id: "focus_short_quiz",
        kind: "QUIZ_SINGLE",
        shape: "circle",
        title: "Recunoaște zgomotul",
        description: "Ce faci când te trezești cu 5 tab-uri deschise?",
        quizOptions: [
          { id: "A", label: "Continui la întâmplare" },
          { id: "B", label: "Închid tot și respir 4 secunde" },
        ],
        correctOptionIds: ["B"],
        xp: 10,
      },
      {
        id: "focus_short_real",
        kind: "REAL_WORLD",
        shape: "star",
        badge: "viata_reala",
        title: "Viața reală",
        description: "Azi, ia 2 minute fără telefon înainte de un task important.",
        xp: 20,
      },
      {
        id: "focus_short_summary",
        kind: "SUMMARY",
        shape: "circle",
        title: "Ancora + sumar",
        description: "Energia mentală se construiește în pauze. Când schimb contextul → respir.",
        xp: 0,
      },
    ],
  },
  clarity_cluster: {
    cluster: "clarity_cluster",
    nodes: [
      {
        id: "clarity_short_intro",
        kind: "INTRO",
        shape: "circle",
        title: "Claritate rapidă",
        description: "Regula celor 7 cuvinte îți curăță mintea de zgomot.",
        xp: 0,
      },
      {
        id: "clarity_short_learn",
        kind: "LEARN",
        shape: "circle",
        title: "Formulează sarcina",
        description: "Scrie în 7 cuvinte ce urmează să faci.",
        xp: 10,
      },
      {
        id: "clarity_short_example",
        kind: "LEARN",
        shape: "circle",
        title: "Exemplu clar vs. vag",
        description: "Vag: „Fac mailuri”. Clar: „Răspund la mailul X cu trei puncte.”",
        xp: 5,
      },
      {
        id: "clarity_short_quiz",
        kind: "QUIZ_SINGLE",
        shape: "circle",
        title: "Test scurt",
        description: "Care propoziție e clară?",
        quizOptions: [
          { id: "A", label: "Văd eu ce fac" },
          { id: "B", label: "Trimit raportul la 14:00" },
        ],
        correctOptionIds: ["B"],
        xp: 10,
      },
      {
        id: "clarity_short_real",
        kind: "REAL_WORLD",
        shape: "star",
        badge: "viata_reala",
        title: "Viața reală",
        description: "Azi, orice sarcină începi, pune-o în 7 cuvinte înainte.",
        xp: 20,
      },
      {
        id: "clarity_short_summary",
        kind: "SUMMARY",
        shape: "circle",
        title: "Ancora + sumar",
        description: "Claritatea creează drum. Formula scurtă îți protejează energia.",
        xp: 0,
      },
    ],
  },
  emotional_flex_cluster: {
    cluster: "emotional_flex_cluster",
    nodes: [
      {
        id: "emoflex_short_intro",
        kind: "INTRO",
        shape: "circle",
        title: "Flexibilitate rapidă",
        description: "Pauza de 2 secunde îți dă libertate emoțională.",
        xp: 0,
      },
      {
        id: "emoflex_short_example",
        kind: "LEARN",
        shape: "circle",
        title: "Trigger comun",
        description: "Primești o critică și reacționezi instant. Asta e reacție automată.",
        xp: 5,
      },
      {
        id: "emoflex_short_learn",
        kind: "LEARN",
        shape: "circle",
        title: "Regula de 2 secunde",
        description: "Inspir 2 secunde, expir 2 secunde. Aleg răspunsul.",
        xp: 10,
      },
      {
        id: "emoflex_short_sim",
        kind: "SIMULATOR",
        shape: "circle",
        badge: "simulator",
        title: "Simulator",
        description: "Pauza de 2 secunde. Încetinești ritmul mental și reduci agitația din tranzițiile dintre activități. Inspiră 2 secunde… expiră 2 secunde.",
        xp: 10,
        simulatorConfig: { inhaleSeconds: 2, exhaleSeconds: 2 },
      },
      {
        id: "emoflex_short_real",
        kind: "REAL_WORLD",
        shape: "star",
        badge: "viata_reala",
        title: "Viața reală",
        description: "Azi, la primul trigger, inspir 2 secunde înainte de a răspunde.",
        xp: 20,
      },
      {
        id: "emoflex_short_summary",
        kind: "SUMMARY",
        shape: "circle",
        title: "Ancora + sumar",
        description: "Între stimul și răspuns e libertatea ta. Pauza te protejează.",
        xp: 0,
      },
    ],
  },
};

export function getDailyPathForCluster(cluster: AdaptiveCluster): DailyPathConfig | null {
  return DAILY_PATHS.find((path) => path.cluster === cluster) ?? null;
}
