import type { DailyPathConfig } from "@/types/dailyPath";

export const CLARITY_ONE_THING_DEEP_EN: DailyPathConfig = {
  id: "clarity_one_important_thing_deep_en",
  cluster: "clarity_cluster",
  mode: "deep",
  lang: "en",
  version: 1,
  moduleKey: "clarity_one_important_thing",
  skillLabel: "Clarity: one important thing",
  autonomyNodeId: "clarity_one_thing_autonomy",
  nodes: [
    {
      id: "clarity_one_thing_intro",
      kind: "INTRO",
      shape: "circle",
      title: "One important thing",
      description:
        "Today you’ll train the most basic clarity skill: choosing one important thing.\nMental noise doesn’t come from lack of intelligence, but from too many priorities at once.",
      xp: 0,
      ctaLabel: "Start training",
    },
    {
      id: "clarity_one_thing_learn1",
      kind: "LEARN",
      shape: "circle",
      title: "Where mental noise comes from",
      description:
        "The mind becomes agitated when it tries to hold too many important things at the same time.\nWhen everything is a priority, nothing is clear.\nClarity begins when you choose one thing that matters now.",
      xp: 5,
    },
    {
      id: "clarity_one_thing_example",
      kind: "LEARN",
      shape: "circle",
      title: "A busy but unclear day",
      description:
        "Alex starts the day with a long list. He jumps between emails, messages, documents, and ideas.\nAt the end of the day he’s tired but can’t say clearly: “This was the important thing today.”\nThe fatigue comes from fragmentation, not from work.",
      xp: 5,
    },
    {
      id: "clarity_one_thing_quiz1",
      kind: "QUIZ_SINGLE",
      shape: "circle",
      title: "Spot the noise",
      description: "What creates the most mental noise?",
      quizOptions: [
        { id: "A", label: "Focused work on one thing." },
        { id: "B", label: "Trying to handle multiple important things at once." },
        { id: "C", label: "Taking a short break." },
      ],
      correctOptionIds: ["B"],
      quizFeedback: {
        correct: "Exactly. Too many simultaneous priorities fragment attention.",
        incorrect: "Not quite. Noise appears when everything feels important.",
      },
      xp: 10,
    },
    {
      id: "clarity_one_thing_learn2",
      kind: "LEARN",
      shape: "circle",
      title: "The one-thing rule",
      description:
        "Clarity doesn’t mean ignoring everything else.\nIt means deciding what matters now.\nThe key question is: “What is the one important thing for the next short period?”",
      xp: 5,
    },
    {
      id: "clarity_one_thing_quiz2",
      kind: "QUIZ_SINGLE",
      shape: "circle",
      title: "Apply it",
      description: "Which sentence shows more clarity?",
      quizOptions: [
        { id: "A", label: "“I have many important things to do.”" },
        { id: "B", label: "“I need to handle everything today.”" },
        { id: "C", label: "“For the next hour, the most important thing is X.”" },
      ],
      correctOptionIds: ["C"],
      quizFeedback: {
        correct: "Yes. Clarity starts when you name one thing.",
        incorrect: "Almost. Clarity requires an explicit choice.",
      },
      xp: 10,
    },
    {
      id: "clarity_one_thing_sim1",
      kind: "SIMULATOR",
      shape: "circle",
      badge: "simulator",
      title: "Simulator: one thing",
      description:
        "While the circle moves, bring to mind everything competing for your attention.\nThen ask: “If I did one thing well right now, what would it be?”\nNotice what happens when everything reduces to one.",
      xp: 15,
      ctaLabel: "Exercise done",
    },
    {
      id: "clarity_one_thing_autonomy",
      kind: "ACTION",
      shape: "star",
      title: "How do you want to continue?",
      description: "Choose your next pace.",
      xp: 0,
    },
    {
      id: "clarity_one_thing_sim2",
      kind: "SIMULATOR",
      shape: "hollow",
      badge: "simulator",
      softPathOnly: true,
      title: "Extra training: final choice",
      description:
        "Form a simple sentence in your mind: “The most important thing for me right now is…”\nNotice if the mind settles.",
      xp: 5,
      ctaLabel: "Exercise done",
    },
    {
      id: "clarity_one_thing_learn3",
      kind: "LEARN",
      shape: "circle",
      title: "How clarity feels",
      description:
        "Clarity doesn’t feel like pressure.\nIt feels like direction, relief, and less mental noise.",
      xp: 5,
    },
    {
      id: "clarity_one_thing_real",
      kind: "REAL_WORLD",
      shape: "star",
      badge: "viata_reala",
      title: "Your real-life challenge",
      description: "Write your context and the one important thing.",
      fields: [
        {
          id: "context",
          label: "Context where I’ll choose one thing:",
          placeholder: "e.g., when I open my laptop in the morning",
        },
        {
          id: "focus",
          label: "The one important thing will be:",
          prefix: "The most important thing right now is ",
          suffix: ".",
          placeholder: "describe the one thing",
        },
      ],
      xp: 25,
      ctaLabel: "I commit",
    },
    {
      id: "clarity_one_thing_summary",
      kind: "SUMMARY",
      shape: "circle",
      title: "Great job — today’s training is complete.",
      description: "",
      bullets: [
        "Mental noise comes from too many priorities at once.",
        "Clarity begins with one important thing.",
        "One clear choice reduces fragmentation.",
      ],
      anchorDescription: "One thing. A clearer mind.",
      xp: 0,
      ctaLabel: "See your progress",
    },
    {
      id: "clarity_one_thing_anchor",
      kind: "ANCHOR",
      shape: "circle",
      title: "Daily motto",
      description: "One thing. A clearer mind.",
      xp: 0,
      ctaLabel: "Done for today",
    },
  ],
};
