import type { DailyPathConfig } from "@/types/dailyPath";

export const CLARITY_ONE_THING_DEEP_RO: DailyPathConfig = {
  id: "clarity_one_important_thing_deep_ro",
  cluster: "clarity_cluster",
  mode: "deep",
  lang: "ro",
  version: 1,
  moduleKey: "clarity_one_important_thing",
  skillLabel: "Claritate: un singur lucru important",
  autonomyNodeId: "clarity_one_thing_autonomy_ro",
  nodes: [
    {
      id: "clarity_one_thing_intro_ro",
      kind: "INTRO",
      shape: "circle",
      title: "Un singur lucru important",
      description:
        "Astăzi lucrăm la cea mai simplă și cea mai ignorată abilitate de claritate: să alegi un singur lucru important.\nZgomotul mental nu vine din lipsă de inteligență, ci din prea multe priorități simultane.",
      xp: 0,
      ctaLabel: "Încep",
    },
    {
      id: "clarity_one_thing_learn1_ro",
      kind: "LEARN",
      shape: "circle",
      title: "De unde apare zgomotul mental",
      description:
        "Mintea devine agitată când încearcă să țină prea multe lucruri importante în același timp.\nCând totul pare prioritar, nimic nu este clar.\nClaritatea începe când alegi un singur lucru care contează acum.",
      xp: 5,
    },
    {
      id: "clarity_one_thing_example_ro",
      kind: "LEARN",
      shape: "circle",
      title: "O zi ocupată, dar neclară",
      description:
        "Alex începe ziua cu o listă lungă. Sare între emailuri, mesaje, documente și idei.\nLa finalul zilei e obosit și nu poate spune clar: „Asta a fost lucrul important de azi.”\nOboseala vine din fragmentare, nu din muncă.",
      xp: 5,
    },
    {
      id: "clarity_one_thing_quiz1_ro",
      kind: "QUIZ_SINGLE",
      shape: "circle",
      title: "Recunoaște zgomotul",
      description: "Ce creează cel mai mult zgomot mental?",
      quizOptions: [
        { id: "A", label: "Să lucrezi concentrat la un singur lucru." },
        { id: "B", label: "Să încerci să faci mai multe lucruri importante în paralel." },
        { id: "C", label: "Să iei o pauză scurtă." },
      ],
      correctOptionIds: ["B"],
      quizFeedback: {
        correct: "Exact. Prea multe priorități simultane fragmentează atenția.",
        incorrect: "Nu chiar. Zgomotul apare când totul devine prioritar.",
      },
      xp: 10,
    },
    {
      id: "clarity_one_thing_learn2_ro",
      kind: "LEARN",
      shape: "circle",
      title: "Regula unui singur lucru",
      description:
        "Claritatea nu înseamnă să ignori restul, ci să decizi ce contează acum.\nÎntrebarea-cheie este: „Care este singurul lucru important în următoarea perioadă scurtă?”\nRestul pot aștepta.",
      xp: 5,
    },
    {
      id: "clarity_one_thing_quiz2_ro",
      kind: "QUIZ_SINGLE",
      shape: "circle",
      title: "Aplică regula",
      description: "Care formulare indică mai multă claritate?",
      quizOptions: [
        { id: "A", label: "„Am multe lucruri importante de făcut.”" },
        { id: "B", label: "„Azi trebuie să mă ocup de toate.”" },
        { id: "C", label: "„În următoarea oră, cel mai important lucru este X.”" },
      ],
      correctOptionIds: ["C"],
      quizFeedback: {
        correct: "Da. Claritatea începe când numești un singur lucru.",
        incorrect: "Aproape. Claritatea cere o alegere explicită.",
      },
      xp: 10,
    },
    {
      id: "clarity_one_thing_sim1_ro",
      kind: "SIMULATOR",
      shape: "circle",
      badge: "simulator",
      title: "Simulator: un singur lucru",
      description:
        "În timp ce cercul se mișcă, adu în minte toate lucrurile care îți cer atenția.\nÎntreabă-te: „Dacă aș face un singur lucru bine acum, care ar fi?”\nObservă ce se întâmplă când reduci totul la unul.",
      xp: 15,
      ctaLabel: "Exercițiul e gata",
    },
    {
      id: "clarity_one_thing_autonomy_ro",
      kind: "ACTION",
      shape: "star",
      title: "Cum vrei să continui?",
      description: "Alege ritmul următor.",
      xp: 0,
    },
    {
      id: "clarity_one_thing_sim2_ro",
      kind: "SIMULATOR",
      shape: "hollow",
      badge: "simulator",
      softPathOnly: true,
      title: "Extra training: clarificarea finală",
      description:
        "Formulează mental o propoziție simplă: „Cel mai important lucru pentru mine acum este…”\nObservă dacă mintea se liniștește.",
      xp: 5,
      ctaLabel: "Exercițiul e gata",
    },
    {
      id: "clarity_one_thing_learn3_ro",
      kind: "LEARN",
      shape: "circle",
      title: "Cum știi că ai claritate",
      description:
        "Claritatea nu se simte ca presiune.\nSe simte ca direcție, ușurare și mai puțin zgomot mental.",
      xp: 5,
    },
    {
      id: "clarity_one_thing_real_ro",
      kind: "REAL_WORLD",
      shape: "star",
      badge: "viata_reala",
      title: "Provocarea ta reală de azi",
      description: "Scrie contextul și singurul lucru important.",
      fields: [
        {
          id: "context",
          label: "Contextul în care voi alege un singur lucru:",
          placeholder: "ex: când deschid laptopul dimineața",
        },
        {
          id: "focus",
          label: "Singurul lucru important va fi:",
          prefix: "Cel mai important lucru acum este ",
          suffix: ".",
          placeholder: "descrie acel lucru",
        },
      ],
      xp: 25,
      ctaLabel: "Mă angajez",
    },
    {
      id: "clarity_one_thing_summary_ro",
      kind: "SUMMARY",
      shape: "circle",
      title: "Felicitări, ai terminat antrenamentul de azi.",
      description: "",
      bullets: [
        "Zgomotul mental vine din prea multe priorități simultane.",
        "Claritatea începe cu un singur lucru important.",
        "O alegere clară reduce fragmentarea mentală.",
      ],
      anchorDescription: "Un singur lucru. O minte mai clară.",
      xp: 0,
      ctaLabel: "Vezi progresul",
    },
    {
      id: "clarity_one_thing_anchor_ro",
      kind: "ANCHOR",
      shape: "circle",
      title: "Motto zilnic",
      description: "Un singur lucru. O minte mai clară.",
      xp: 0,
      ctaLabel: "Gata pe azi",
    },
  ],
};
